name: sporty
description: App sporty per dispositivi mobili

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.1+1
  get: ^4.6.5
  google_fonts: ^4.0.3
  eva_icons_flutter: ^3.1.0
  awesome_extensions: ^2.0.5
  window_manager: ^0.3.0
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
  rounded_loading_button: ^2.0.8
  email_validator: '^2.1.16'
  http: ^0.13.5
  fading_edge_scrollview: ^3.0.0
  rive: ^0.10.3
  auto_size_text: ^3.0.0
  qr_flutter: ^4.0.0
  intl: ^0.18.0
  collection: 
  transparent_image: ^2.0.1
  photo_view: ^0.14.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  flutter_smart_dialog: ^4.9.0+5
  confetti: ^0.7.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.0
  expandable_page_view: ^1.0.17
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
      - assets/images/backgrounds/
      - assets/images/logo/
      - assets/animations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
